const initialState = {
  filters: {
    queries: "",
    categories: [],
    authors: [],
  },
  blogs: [
    {
      id: 1,
      category: "Article",
      title: "Boost your conversion rate",
      author: "Learn with sumit",
      img: "https://images.unsplash.com/photo-1496128858413-b36217c2ce36?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1679&q=80",
      auth_img: "https://avatars.githubusercontent.com/u/73503432?v=4",
      date: "11 Jul, 2022 ·6 min read",
    },
    {
      id: 2,
      category: "Article",
      title: "How to use search engine optimization to drive sales",
      author: "Learn with sumit",
      img: "https://images.unsplash.com/photo-1547586696-ea22b4d4235d?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1679&q=80",
      auth_img: "https://avatars.githubusercontent.com/u/73503432?v=4",
      date: "08 Feb, 2022 ·11 min read",
    },
    {
      id: 3,
      category: "Article",
      title: "Improve your customer experience",
      author: "Learn with sumit",
      img: "https://images.unsplash.com/photo-1492724441997-5dc865305da7?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1679&q=80",
      auth_img: "https://avatars.githubusercontent.com/u/73503432?v=4",
      date: "20 Mar, 2022 ·9 min read",
    },
    {
      id: 4,
      category: "Business",
      title: "The Best Business Blogs Every Entrepreneur Should Be Reading",
      author: "Kevin Fowler",
      img: "https://i.ibb.co/hBRbFSZ/Blog.jpg",
      auth_img: "https://i.ibb.co/5hW2gRt/Edtkjwp-VAAE7rj-Z.png",
      date: "April 05, 2019 ·20 min read",
    },
    {
      id: 5,
      category: "Business",
      title: "3 Ways to Reduce the Stress of Small Business Payment Processing",
      author: "Julia Olson",
      img: "https://i.ibb.co/6DN1tBB/3-ways-to-reduce-stress-small-business-payment-processing-1024x688.jpg",
      auth_img: "https://i.ibb.co/HhBq2Yg/juliaheadshot.jpg",
      date: "April 19, 2021 ·12 min read",
    },
    {
      id: 6,
      category: "Sports",
      title:
        "Luka Modric still at very top and World Cup has enhanced his legacy",
      author: "Nick Ames",
      img: "https://i.ibb.co/ssv1D2b/5338.webp",
      auth_img: "https://i.ibb.co/5TPCdXy/Nick-Ames.webp",
      date: "13 Dec 2022 ·8 min read",
    },
    {
      id: 7,
      category: "Sports",
      title:
        "Globalise the final round of qualifying and a 32-nation World Cup may still add up",
      author: "Jonathon Wilson",
      img: "https://i.ibb.co/xGwxdCj/3500.webp",
      auth_img: "https://i.ibb.co/FXGBNvb/images.jpg",
      date: "11 Dec 2022 ·15 min read",
    },
    {
      id: 8,
      category: "Sports",
      title:
        "Julián Álvarez evokes Argentina’s spirit of Kempes and can resurrect old glories",
      author: "Jonathon Wilson",
      img: "https://i.ibb.co/87gSY9V/4467.webp",
      auth_img: "https://i.ibb.co/FXGBNvb/images.jpg",
      date: "17 Dec 2022 ·7 min read",
    },
    {
      id: 9,
      category: "Food",
      title: "Rachel Roddy’s recipe for zabaione",
      author: "Rachel Roddy",
      img: "https://i.ibb.co/TmKQwRr/3000.webp",
      auth_img: "https://i.ibb.co/qr6Nb1n/Rachel-Roddy-L.webp",
      date: "19 Dec 2022 ·11 min read",
    },
    {
      id: 10,
      category: "Food",
      title: "Christmas fizz to add some sparkle to your festive celebrations",
      author: "Rachel Roddy",
      img: "https://i.ibb.co/gRv0FMQ/5760.webp",
      auth_img: "https://i.ibb.co/qr6Nb1n/Rachel-Roddy-L.webp",
      date: "19 Dec 2022 ·15 min read",
    },
  ],
};
export default initialState;
